parameters:

    # Service Parameters defined in app/config

services:

    #
    # Gateways.
    #
    ccdn_user_security.gateway.session:
        class: "%ccdn_user_security.gateway.session.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%ccdn_user_security.entity.session.class%"
