version: '2'

services:
  mysql:
    image: mysql:5.5
    environment:
        MYSQL_ROOT_PASSWORD: "changeme"
        MYSQL_USER: ccdnroot
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: ccdn_test
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./:/app

  php-fpm:
    build: docker/php
    volumes:
      - ./:/app
    working_dir: /app
